server:
  port: 8081

app:
  demo-data:
    enabled: ${DEMO_DATA_ENABLED:true}

spring:
  application:
    name: event-service
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:ticketing_db}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer